name: Closed PRs Reporter
description: Report closed pull requests on GitHub repository.
author: Shivam 
branding:
  icon: clipboard
  color: blue
inputs:
  GITHUB_OWNER:
    description: 'GitHub repository owner.'
    required: true
  GITHUB_REPO:
    description: 'GitHub repository name.'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token for authentication.'
    required: true
  GITHUB_BRANCH:
    description: 'Base branch name.'
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.GITHUB_OWNER }}
    - ${{ inputs.GITHUB_REPO }}
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.GITHUB_BRANCH }}
