name: Closed PRs Reporter
description: Report closed pull requests on GitHub repository.
author: Your Name
branding:
  icon: clipboard
  color: blue
inputs:
  GITHUB_OWNER:
    description: 'GitHub repository owner.'
    required: true
  GITHUB_REPO:
    description: 'GitHub repository name.'
    required: true
  INPUT_GITHUB_TOKEN:
    description: 'GitHub token for authentication.'
    required: true
  INPUT_GITHUB_BRANCH:
    description: 'Base branch name.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'